language: python

python:
  - 2.7
  - 3.4

notifications:
  email: false
 
# Setup anaconda
before_install:

#  - wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a
  - sudo apt-get update

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas 
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls
  - pip install coveralls
  - pip install ez_setup
  - python setup.py install
 
# Run test
script:
#  - nosetests --with-cov --cov gammatools --cov-config .coveragerc --logging-level=INFO
  - nosetests --with-coverage --logging-level=INFO
 
# Calculate coverage
after_success:
#  - coveralls --config_file .coveragerc
  - coveralls

